# .github/workflows/deploy.yml
name: Deploy to Vercel
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  NEXT_PUBLIC_FIREBASE_API_KEY: 'AIzaSyC6yRbCjSJCc0ruPbiP9vIPykP0018v5BM'
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: 'skill-tracker-67382.firebaseapp.com'
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: 'skill-tracker-67382'
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: 'skill-tracker-67382.firebasestorage.app'
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: '69878243836'
  NEXT_PUBLIC_FIREBASE_APP_ID: '1:69878243836:web:f59ee297a86027c09aee25'
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: 'G-MP1S35KVWZ'

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}